Default: &defaults
  host: "alistra.ath.cx"
  port: 3001

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.alistra.ath.cx"
  <<: *defaults
